Inteligene/Inteligene/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.App_1.urls')),
]

Inteligene/applications/App_1/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'App1_app'
urlpatterns = [
    path('', views.EntradasListView.as_view(), name = 'inicio'),
    path('home/', views.EntradasListView.as_view(), name = 'inicio'),
    path('new_Entrada/', views.EntradaCreateView.as_view(), name = 'Nueva-Entrada'),
    path('editar/<pk>/', views.Editar_Entradas.as_view(), name = 'Editar-Entrada'),
    path('eliminar_entrada/<pk>/', views.EntradaDelete.as_view(), name = 'Eliminar-Entrada'),
    path('ver_entrada/<id_entrada>/', views.VerEntrada.as_view(), name = 'Ver-Entrada'),

]

Inteligene/applications/App_1/models.py
from django.db import models
#apps terceros
from model_utils.models  import TimeStampedModel
# Create your models here.

class Entrada(TimeStampedModel):
    autor = models.CharField('Autor', max_length=50)
    titulo = models.CharField('Titulo', max_length=50)
    cuerpo = models.TextField()

    class Meta:
        verbose_name= 'Entrada'
        verbose_name_plural= 'Entradas' ##DECORADORES
        ordering = ['-id'] #Agregar orden
        unique_together = ('autor', 'cuerpo') #No queremos que se registren dos parametros iguales en un registro


    def __str__(self):
        return str(self.id) + '-' + self.autor + '-' +self.titulo

class Comentario(TimeStampedModel):
    c_autor = models.CharField('Autor', max_length=50)
    c_cuerpo = models.TextField()
    id_Entrada = models.ForeignKey(Entrada, on_delete=models.CASCADE)

    class Meta:
        verbose_name= 'Comentario'
        verbose_name_plural= 'Comentarios' ##DECORADORES

    def __str__(self):
        return str(self.id) + '-' + str(self.id_Entrada) + ' '+ self.c_autor

class Subcomentario(TimeStampedModel):
    subc_autor = models.CharField('Autor', max_length=50)
    subcc_cuerpo = models.TextField()
    id_comment = models.ForeignKey(Comentario, on_delete=models.CASCADE)

    class Meta:
        verbose_name= 'Subcomentario'
        verbose_name_plural= 'Subcomentarios' ##DECORADORES

        
        def __str__(self):
            return str(self.id) 

Inteligene/applications/App_1/forms.py
#AQUI ESCRIBIREMOS LAS PERSONALIZACIONES DE LOS FORMLARIOS 

from django import forms
from .models import Comentario, Entrada


#FORMULARIO QUE PARTE DE UN MODELO HEREDANDO LOS ATRIBUTOS Y CARACTERISTICAS DE ESTE

class SetFormEntrada(forms.ModelForm):
    """Form definition for MODELNAME."""

    class Meta:
        """Meta definition for MODELNAMEform."""

        model = Entrada
        fields = ('autor','titulo','cuerpo')

        widgets ={
            'titulo': forms.TextInput(
                attrs = {
                    'placeholder': 'Titulo de la publicación',
                }
            )
            ,
            'autor': forms.TextInput(
                attrs = {
                    'placeholder': 'Autor',
                }
            ),
        }


class SetFormComentario(forms.ModelForm):
    """Form definition for MODELNAME."""

    class Meta:
        """Meta definition for MODELNAMEform."""

        model = Comentario
        fields = ('c_autor','c_cuerpo',)

        widgets ={

            'c_autor': forms.TextInput(
                attrs = {
                    'placeholder': 'Autor',
                }
            ),
        }

Inteligene/applications/App_1/views.py
from django.db import models
from django.shortcuts import render
from django.urls import reverse_lazy
from itertools import chain
from django.views.generic import *
from .models import Entrada, Comentario
from .forms import SetFormEntrada, SetFormComentario


# Create your views here.


class EntradaCreateView(CreateView):
    model = Entrada
    template_name = "principal/crear_entrada.html"
    form_class = SetFormEntrada
    success_url= reverse_lazy('App1_app:inicio')

    def form_valid(self, form):

        form.save() #Con esto ejecutamos el registtro. se puede anular con 'commit = False'
        return super().form_valid(form)

class EntradasListView(ListView):
    model = Entrada
    template_name = "principal/home.html"
    context_object_name = 'entradas'


class Editar_Entradas(UpdateView):
    model = Entrada
    template_name = "principal/editar.html"
    fields=['autor','titulo','cuerpo']
    success_url= reverse_lazy('App1_app:inicio')

class EntradaDelete(DeleteView):
    model = Entrada
    template_name = "principal/delete.html"
    success_url= reverse_lazy('App1_app:inicio')
    

class VerEntrada(CreateView):
    template_name = "principal/ver_entrada.html"
    context_object_name = 'entrada'
    model = Comentario
    success_url= reverse_lazy('App1_app:inicio')
    form_class =SetFormComentario
    
    

    def form_valid(self, form):
        print('############## METODO FORM VALID###########################')
        id_entrada = self.kwargs['id_entrada']
        objeto_entrada = Entrada.objects.get(id=id_entrada)
        print(objeto_entrada)
        form.instance.id_Entrada = objeto_entrada
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        id_entrada = self.kwargs['id_entrada']
        objeto_entrada = Entrada.objects.get(id=id_entrada)
        comentarios= Comentario.objects.filter(id_Entrada=objeto_entrada)
        context['comentarios'] = comentarios
        context['entradas'] = objeto_entrada
        return context
    

Inteligene/templates/base.html
{% load static%}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <title> {% block title %} {% endblock title  %} </title>
</head>
<body>
    {% block content %} 
    
    {% endblock content  %} 

    <script  src = "{% static 'js/vendor/jquery.js' %}"src=""></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.min.js' %}    "></script>
    <script>
        $(document).foundation();
      </script>
</body>
</html>

Inteligene/templates/header.html
{% load static%}

<div class="top-bar">
    <div class="top-bar-left">
      <ul class="menu">
        <li><a class="button warning" href="{% url 'App1_app:inicio' %}">Inicio</a></li>
      </ul>
    </div>
  </div>

Inteligene/templates/principal/crear_entrada.html
{% extends 'base.html' %}


{% block title %}
    Crear nueva entrada
{% endblock title %}
    

{% block content %}

{% include 'header.html' %}

<div class="grid-content">
    <div class="grid-x align-center">
        <h1 class="cell large-5">Agregar una publicación</h1>
        <form action="" class="cell large-8" method="POST"> {% csrf_token %}

            <div class="cell large-4">
                {{form}}
            </div>
        <div class="cell">
            <input type="submit"  class="button success" value="Comentar">
        </div>

        </form>
    </div>
</div>

{% endblock content %}
    

Inteligene/templates/principal/delete.html
{% extends 'base.html' %}



{% block blockname %}
    Eliminar Entrada
{% endblock blockname %}


{% block content %}
{% include 'header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar Entrada</h1>
        <form  class= "cell" action="" method="post"> {% csrf_token %}
            
            <div class="callout secondary">
                <h5>Desea eliminar esta entrada: </h5>
                <p>{{object.titulo}} {{object.autor}}</p>
            </div>

            <input  class="button alert" type="submit" value="Eliminar">
            
        </form>
    </div>
</div>

{% endblock content %}

Inteligene/templates/principal/editar.html
{% extends 'base.html' %}


{% block title %}
    Editar Entrada
{% endblock title %}


{% block content %}
{% include 'header.html' %}

<div class="grid-content">
    <div class="grid-x align-center">
        <h1 class="cell large-8">Editar entrada</h1>
        <form  class= "cell large-8" action="" method="POST"> {% csrf_token %}
            {{form.as_p}}
            <input  class="button primary" type="submit" value="Actualizar">
        </form>
    </div>
</div>

{% endblock content %}
    
    

Inteligene/templates/principal/home.html
{% extends 'base.html' %}
{% load static%}


{% block title %}
    Inicio
{% endblock title %}


{% block content %}
<div class="top-bar">
    <div class="top-bar-right">
      <ul class="menu">
        <li><a class="button warning" href="{% url 'App1_app:Nueva-Entrada' %}">Registrar</a></li>
      </ul>
    </div>
</div>

<div class="grid-x align-center">
    <div class="cell">
        <div class="content-card">
            
                {% for e in entradas %}
                <div class="widgets">
                    <div class="text_card">
                        <p class="autor_card ">{{e.autor}}<p>
                        <p class="titulo_card">{{e.titulo}}</p>
                        <p class="cuerpo_card">{{e.cuerpo}}</p>
                    </div>
                    <div class="button_card">
                        <div class="group_button">
                            <a class="button secondary" href="{% url 'App1_app:Ver-Entrada' e.id %}">Ver</a>
                            <a class="button secondary" href="{% url 'App1_app:Editar-Entrada' e.id %}">Editar </a>
                            <a class="button secondary" href="{% url 'App1_app:Eliminar-Entrada' e.id %}">Eliminar</a>
                        </div>
                        
                        <!-- <div class="boton_card" ><a href="">Ver Publicacion</a></div>
                        <div class="boton_card" ><a href="">Editar</a></div>
                        <div class="boton_card" ><a href="">Eliminar</a></div> -->
                    </div>  
                    
                </div>
                {% endfor %}
            
        </div>
    </div>
</div>



{% endblock content %}
    
    

Inteligene/templates/principal/ver_entrada.html
{% extends 'base.html' %}



{% block title %}
    Ver entrada
{% endblock title %}


{% block content %}
{% include 'header.html' %}

<div class="grid-content">
    <div class="grid-x align-center">
        <h3 class="cell large-8">
            <i>{{entradas.autor}} -  </i> <b>{{entradas.titulo}} </b>
        </h3>
        <div class="cell large-8">
            {{entradas.cuerpo}}
        </div>
    </div>
    <hr>
    <div class="grid-x align-center">
        <h3 class="cell large-8" >Comentarios</h3>
        <div class="cell large-8">
            {% for e in comentarios %}
                <hr class="solid">
               <p><b>{{e.c_autor}}</b> </p> 
                <p>{{e.c_cuerpo}}</p>


                
            {% endfor %}
        </div>
    </div>
    <hr>
    <div class="grid-x align-center">
        <h4 class="cell large-8"> Agregar un comentario</h4>     
            <form action="" method="post" class="cell large-8"> {% csrf_token %}
                {{form.c_autor}}
                <label > Escribe tu comentario</label>
                {{form.c_cuerpo}}
                

                <input type="submit"  class="button success" value="Comentar">
                <button type="reset" class="button secondary" >Limpiar</button>
            </form>
    </div>

</div>


{% endblock content %}
    
    